[package]
name = "fractal_clock"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
eframe = { version = "0.32.0", features = ["persistence", "serde"] }
egui = "0.32.0"
image = "0.25.6"
serde = { version = "1.0.219", features = ["derive"] }
